### ISSUE TITLE
v1 Tracking Issue

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/statusphere-example-app#2]
- [ ] Implement revision tracking (see https://github.com/bluesky-social/atproto-express-app/pull/3#discussion_r1714585229)
- [ ] Ensure the firehose is correctly backfilling
- [x] Possibly move the firehose implementation upstream
- [ ] Resolve need for validate: false in repo write
- [ ] Resolve the node v22 requirement in the OAuth library
- [x] Decide on bskyagent
- [ ] Add sugars to atproto agent
- [ ] Handle account deactivations and deletions
- [x] Reorganize the repo for simplicity
- [x] Implement the application backend & frontend
- [x] Implement lexicon tooling
- [x] Fetch & highlight the user's current status
- [x] Factor out the session restoration logic in get('/')
- [x] Replace the did_cache table with MemoryCache (in the resolver)
- [x] Switch off pnpm to npm
- [x] Add an env variable for setting the database
- [ ] Finalize setup instructions
- [x] Write a tutorial
